# Pytorch Tutorial
Tensors Basics
    A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [4]:
import torch

In [5]:
torch.__version__

'2.0.1'

In [6]:
import numpy as np

In [11]:
list=[1,3,4,5,6,8,7]
array=np.array(list)

In [12]:
array

array([1, 3, 4, 5, 6, 8, 7])

In [13]:
array.dtype

dtype('int64')

In [14]:
ll=['3,5,7,78']

In [18]:
arr=np.array(ll)
arr


array(['3,5,7,78'], dtype='<U8')

In [21]:
arr.dtype

dtype('<U8')

In [29]:
tensors[3]=100

In [30]:
tensors

tensor([  1,   3,   4, 100,   6,   8,   7])

In [31]:
array

array([  1,   3,   4, 100,   6,   8,   7])

In [33]:
###prevnent this by using torch.tensor

In [36]:
tensor_arr=torch.tensor(array)

In [37]:
tensor_arr

tensor([  1,   3,   4, 100,   6,   8,   7])

In [39]:
tensor_arr[3]=200
print(tensor_arr)
print(array)

tensor([  1,   3,   4, 200,   6,   8,   7])
[  1   3   4 100   6   8   7]


In [40]:
# zeros and ones

In [41]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [42]:
torch.ones(3,4,dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [47]:
a=torch.tensor(np.arange(0,15).reshape(3,5))

In [48]:
a

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [51]:
a[:,1:4]

tensor([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13]])

# Arithmetic Operations

In [52]:
a=torch.tensor([3,4,5,6],dtype=torch.float64)

In [53]:
b=torch.tensor([7,7,4,3],dtype=torch.float64)

In [54]:
print(a+b)

tensor([10., 11.,  9.,  9.], dtype=torch.float64)


In [56]:
torch.add(a,b)

tensor([10., 11.,  9.,  9.], dtype=torch.float64)

In [62]:
c=torch.zeros(3)

In [63]:
torch.add(a,b,out=c)

/tmp/ipykernel_24338/3773876854.py:1: UserWarning: An output with one or more elements was resized since it had shape [3], which does not match the required output shape [4]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /croot/pytorch_1686931851744/work/aten/src/ATen/native/Resize.cpp:26.)
  torch.add(a,b,out=c)


tensor([10., 11.,  9.,  9.])

In [64]:
##some more operations

In [66]:
torch.add(a,b).sum()

tensor(39., dtype=torch.float64)

##Dot Products and Mult Operations 

In [70]:
x=torch.tensor([5,6,7,3,9],dtype=torch.float)

In [71]:
y=torch.tensor([9,4,2,1,7],dtype=torch.float)

In [72]:
x.mul(y)

tensor([45., 24., 14.,  3., 63.])

In [73]:
torch.mul(x,y)

tensor([45., 24., 14.,  3., 63.])

In [74]:
x.dot(y)

tensor(149.)

In [75]:
torch.dot(x,y)

tensor(149.)

# Matrix Multiplications


In [81]:
i=torch.tensor([[4,6,4],[4,574,7]],dtype=torch.float)
j=torch.tensor([[4,2],[5,7],[43,26]],dtype=torch.float)

In [82]:
torch.matmul(i,j)

tensor([[ 218.,  154.],
        [3187., 4208.]])

In [83]:
torch.mm(i,j)

tensor([[ 218.,  154.],
        [3187., 4208.]])

In [85]:
i@j   #(@) short form of matrix multiplictaions

tensor([[ 218.,  154.],
        [3187., 4208.]])