y=x^2

In [4]:
import torch

In [5]:
x=torch.tensor(4.0,requires_grad=True)

In [6]:
x

tensor(4., requires_grad=True)

In [7]:
y=x**2

In [8]:
y

tensor(16., grad_fn=<PowBackward0>)

# Back Propagation y=x*2

In [9]:
y.backward()

In [14]:
print(x.grad)

tensor(8.)


In [26]:
list=[[2,3,4],[3,8,9],[9,4,5]]
torch_input=torch.tensor(list,requires_grad=True,dtype=torch.float)

In [27]:
torch_input

tensor([[2., 3., 4.],
        [3., 8., 9.],
        [9., 4., 5.]], requires_grad=True)

In [46]:
##y=x**3+x**2 (initaily)
##y=3x**2+2x (after one back propogation)

In [47]:
h=3*2**2+2*2
j=3*3**2+2*3

In [48]:
print(h)
print(j)

16
33


In [49]:
 y=torch_input**3+torch_input**2

In [50]:
y


tensor([[ 12.,  36.,  80.],
        [ 36., 576., 810.],
        [810.,  80., 150.]], grad_fn=<AddBackward0>)

In [51]:
z=y.sum()

In [52]:
z

tensor(2590., grad_fn=<SumBackward0>)

In [53]:
z.backward()

In [54]:
torch_input.grad

tensor([[ 32.,  66., 112.],
        [ 66., 416., 522.],
        [522., 112., 170.]])